INSERT INTO items (title, description, price, image_path) VALUES ('Бейсболка чёрная', 'Классическая бейсболка из хлопка с регулируемым размером.', 990, 'black-cap.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Бейсболка красная', 'Яркая хлопковая бейсболка с регулируемым размером.', 990, 'red-cap.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Футбольный мяч', 'Классический футбольный мяч, размер 5.', 1990, 'soccer-ball.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Зонт-трость чёрный', 'Большой зонт-трость с автоматическим механизмом открытия.', 1490, 'umbrella.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Пивная кружка', 'Гранёная стеклянная пивная кружка объёмом 0,5 литра.', 590, 'beer-mug.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Шотландский килт', 'Традиционный шотландский килт из шерсти в красную клетку.', 6900, 'kilt.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Шотландская волынка', 'Традиционная шотландская волынка с чехлом в красную клетку.', 24900, 'bagpipes.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Бейсболка Boston Bruins', 'Кепка с логотипом хоккейного клуба Boston Bruins.', 2490, 'bruins-cap.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Волейбольный мяч Mikasa V200W', 'Волейбольный мяч', 5990, 'volleyball.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Волейбольный мяч Demix V700', 'Волейбольный мяч', 2490, 'volleyball-demix.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Мяч для американского футбола Wilson', 'Мяч для американского футбола', 3490, 'football-american.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Мяч для регби Gilbert Virtuo', 'Мяч для регби', 4290, 'rugby-ball.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Теннисные мячи FILA Ultimate', 'Теннисные мячи', 590, 'tennis-ball-fila.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Теннисные мячи HEAD T.I.P', 'Теннисные мячи, набор', 790, 'tennis-balls-head.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Массажный мяч', 'Массажный мяч', 890, 'massage-ball.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Ракетка для настольного тенниса 729', 'Ракетка для настольного тенниса', 1490, 'table-tennis-racket.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Теннисная ракетка Torneo Pulse ALU', 'Теннисная ракетка', 2990, 'tennis-racket-torneo.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Ракетка для падела Legend', 'Ракетка для падела', 3990, 'padel-racket.png');
INSERT INTO items (title, description, price, image_path) VALUES ('Теннисная ракетка HEAD', 'Теннисная ракетка', 4490, 'tennis-racket-head.png');
