DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    account_id BIGINT NOT NULL
);

CREATE TABLE items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price       BIGINT NOT NULL,
    image_path  VARCHAR(255)
);

CREATE TABLE cart_items (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    count   INT NOT NULL,
    CONSTRAINT uq_cart_items_user_item UNIQUE (user_id, item_id),
    CONSTRAINT fk_cart_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE orders (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_sum BIGINT NOT NULL
);

CREATE TABLE order_items (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id  BIGINT NOT NULL,
    count    INT NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_item FOREIGN KEY (item_id) REFERENCES items (id)
);
