server:
  port: 8080

app:
  items-page:
    row-size: 3
  images-base-path: images/

spring:
  application:
    name: my-market-app
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
